// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7r-TzQm2J4-EvI-H6jphfncVx9uHBrsQ',
    appId: '1:352111075138:web:8212a46ed31426658c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    authDomain: 'myprotfolio-a0b51.firebaseapp.com',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
    measurementId: 'G-R7CYHYP7GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZde0dFPtnWo7rrB-FasrfMADRBCjg3Os',
    appId: '1:352111075138:android:0137259aa56d24fc8c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKsQrNh8jeeLHZXwqc1O2nAZpAxTbpCU',
    appId: '1:352111075138:ios:abcda53d84d77c998c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwKsQrNh8jeeLHZXwqc1O2nAZpAxTbpCU',
    appId: '1:352111075138:ios:abcda53d84d77c998c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7r-TzQm2J4-EvI-H6jphfncVx9uHBrsQ',
    appId: '1:352111075138:web:8a6e6fe667d075378c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    authDomain: 'myprotfolio-a0b51.firebaseapp.com',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
    measurementId: 'G-3JMB0LCDRF',
  );
}
